baseURL: 'https://sazidthe1.github.io/'
title: Sazidul Islam
theme: PaperMod
paginate: 5
theme: PaperMod
publishDir: "docs"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: experience
      name: Experience
      url: /experience/
      weight: 40
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 50
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 60

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: sazid.me
  description: "Welcome to Sazid.me"
  keywords: [Portfolio, Blog, Data]
  #author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "Jan, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
   disableHLJS: true # to disable highlight.js
   disableFingerprinting: true
  favicon: "<link rel='icon' type='image/x-icon' href='/static/favicon.ico'>"

  label:
    text: "sazid"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Sazidul Islam"
    subtitle:
      Hey! 👋 I'm Sazid, an Aspiring Dev.

      I find joy in working with data that positively impacts people's lives.

      I'm a data science and machine learning enthusiast who is also passionate about open source, and sharing knowledge with others.

      When I'm not coding or learning something new, I spend my time cycling, reading, and listening to podcasts. If any of these interests resonate with you, I'd love to chat!

    imageUrl: "home/sazid.jpeg"
    imageWidth: 155
    imageHeight: 155
    imageTitle: "sazid's image"
    buttons:
    #  - name: Posts
     #   url: posts

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my profile!

  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sazidthe1"
    - name: "twitter"
      url: "https://twitter.com/sazidthe1"
    - name: "github"
      url: "https://github.com/sazidthe1"
    - name: "kaggle"
      url: "https://www.kaggle.com/sazidthe1"
    - name: "medium"
      url: "https://medium.com/@sazidthe1"
    #- name: "email"
    #  url: "mailto:sazidulislam29@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page


# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
