baseURL: 'https://sazidthe1.github.io/'
title: Sazidul Islam
theme: PaperMod
paginate: 5
theme: PaperMod
publishDir: "docs"

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
    - identifier: posts
      name: posts
      url: /posts
      weight: 30
    - identifier: contact
      name: contact
      url: /contact/
      weight: 40

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: sazid.me
  description: "Welcome to Sazid.me!"
  keywords: [Blog, Data, Portfolio]
  # author: "Sazid"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
   disableHLJS: true # to disable highlight.js
   disableFingerprinting: true
  favicon: "<link rel='icon' type='image/x-icon' href='/static/favicon.ico'>"

  label:
    text: "sazid"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Sazidul Islam"
    subtitle:
      Hey! 👋 I'm Sazid, a Data Analyst at MMC in Asia. 🌏

      I find joy in working with data that positively impacts people's lives. 
      
      I'm keen on data, open source, and sharing knowledge with others.

      In addition to working with data and learning new things, I enjoy cycling, reading, and listening to podcasts. I'd love to chat if any of these interests resonate with you!

    imageUrl: "home/sazid.jpeg"
    imageWidth: 155
    imageHeight: 155
    imageTitle: "sazid's image"
    buttons:
    #  - name: Posts
     #   url: posts

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my profile!

  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/sazidthe1"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sazidthe1/"
    - name: "github"
      url: "https://github.com/sazidthe1"
    - name: "kaggle"
      url: "https://www.kaggle.com/sazidthe1"
    - name: "dev"
      url: "https://sazidthe1.hashnode.dev/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai